apiVersion: v1
appVersion: master
description: Grafana-operator Helm chart for Kubernetes
home: https://github.com/integr8ly/grafana-operator
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
keywords:
- grafana
- operator
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: grafana-operator
version: 0.3.16
