apiVersion: v1
appVersion: 2.2.2
description: A Helm chart for Emissary Ingress
home: https://www.getambassador.io/
icon: https://www.getambassador.io/images/logo.png
keywords:
- api gateway
- ambassador
- datawire
- envoy
- emissary
- emissary ingress
maintainers:
- email: markus@maga.se
  name: flydiverny
- email: flynn@datawire.io
  name: kflynn
- email: nkrause@datawire.io
  name: nbkrause
- email: lukeshu@datawire.io
  name: lukeshu
name: emissary-ingress
sources:
- https://github.com/datawire/ambassador
- https://github.com/prometheus/statsd_exporter
version: 7.3.2
