apiVersion: v1
name: istiod
version: 1.0.3
appVersion: 1.0.3
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
sources:
  - https://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
