{{- if .Values.oauthProxy.enabled -}}
{{- $fullName := .Values.oauthProxy.serviceName -}}
{{- $svcPort := .Values.oauthProxy.servicePort -}}
{{- $authNamespace := .Values.oauthProxy.namespace -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "gpm-{{ $fullName }}"
  namespace: {{ $authNamespace }}
  labels:
    {{- include "gatekeeper-policy-manager.labels" . | nindent 4 }}
  {{- with .Values.oauthProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.oauthProxy.tls }}
  tls:
    {{- range .Values.oauthProxy.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.oauthProxy.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
