{{- if .Values.cert_manager.setup_letsencrypt_prod_cluster_issuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-prod"
  labels:
    app: {{ template "bluescape-eks-aux.name" . }}
    chart: {{ template "bluescape-eks-aux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ops@bluescape.com
    # Name of a secret used to store the ACME account private key
    preferredChain: ISRG Root X1
    # preferredChain option will allow you to specify a CA’s common name for the certificate to be issued by
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
