{{- if .Values.cert_manager.setup_letsencrypt_prod_cluster_dns_issuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name:   "letsencrypt-prod-dns"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  acme:
    email: ops@bluescape.com
    preferredChain: ISRG Root X1
    # preferredChain option will allow you to specify a CA’s common name for the certificate to be issued by
    privateKeySecretRef:
      name: letsencrypt-production-dns
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          route53:
            accessKeyID: ''
            region: us-west-2
            role: ''
            secretAccessKeySecretRef:
              name: ''
        selector: {}
{{- end }}