{{- if .Values.external_secrets.setup_aes_edge_stack_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ if eq .Values.external_secrets.aes_edge_stack_secret_name "" }}{{ .Release.Name }}{{ else }}{{ .Values.external_secrets.aes_edge_stack_secret_name }}{{ end }}
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: license-key
      key: secret/data/aes-edge-stack
      property: license-key
{{- end }}

{{- if .Values.external_secrets_operator.setup_aes_edge_stack_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: {{ if eq .Values.external_secrets_operator.aes_edge_stack_secret_name "" }}{{ .Release.Name }}{{ else }}{{ .Values.external_secrets_operator.aes_edge_stack_secret_name }}{{ end }}
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: {{ if eq .Values.external_secrets_operator.aes_edge_stack_secret_name "" }}{{ .Release.Name }}{{ else }}{{ .Values.external_secrets_operator.aes_edge_stack_secret_name }}{{ end }}
  data:
  - secretKey: license-key
    remoteRef:
      key: aes-edge-stack
      property: license-key
{{- end }}

