{{- if .Values.external_secrets.setup_legacy_extra_cluster_issuer_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Values.external_secrets.cluster_issuer_name }}"
  namespace: cert-manager
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: accessKeyId
      key: secret/data/certmanager/{{ .Values.external_secrets.cluster_issuer_name }}/aws-route53-creds
      property: accessKeyId
    - name: secretAccessKey
      key: secret/data/certmanager/{{ .Values.external_secrets.cluster_issuer_name }}/aws-route53-creds
      property: secretAccessKey
{{- end }}
{{- if .Values.external_secrets_operator.setup_legacy_extra_cluster_issuer_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "{{ .Values.external_secrets_operator.cluster_issuer_name }}"
  namespace: cert-manager
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.external_secrets_operator.cluster_issuer_name }}"
  data:
  - secretKey: accessKeyId
    remoteRef:
      key: certmanager/{{ .Values.external_secrets_operator.cluster_issuer_name }}/aws-route53-creds
      property: accessKeyId
  - secretKey: secretAccessKey
    remoteRef:
      key: certmanager/{{ .Values.external_secrets_operator.cluster_issuer_name }}/aws-route53-creds
      property: secretAccessKey
{{- end }}