{{- if .Values.external_secrets.setup_loki_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "loki-ingress-auth"
  namespace: loki
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: auth
      key: secret/data/logging/loki
      property: ingress-auth
{{- end }}

{{- if .Values.external_secrets_operator.setup_loki_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "loki-ingress-auth"
  namespace: "loki"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "loki-ingress-auth"
  data:
  - secretKey: auth
    remoteRef:
      key: logging/loki
      property: ingress-auth
{{- end }}