{{- if .Values.external_secrets.setup_prometheus_metrics_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "metrics"
  namespace: monitoring
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: password
      key: secret/data/prometheus/metrics
      property: password
    - name: username
      key: secret/data/prometheus/metrics
      property: username
{{- end }}
{{- if .Values.external_secrets_operator.setup_prometheus_metrics_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "metrics"
  namespace: "monitoring"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "metrics"
  data:
  - secretKey: password
    remoteRef:
      key: prometheus/metrics
      property: password
  - secretKey: username
    remoteRef:
      key: prometheus/metrics
      property: username
{{- end }}