{{- if .Values.external_secrets.setup_threatstack_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "threatstack"
  namespace: threatstack
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: licensekey
      key: secret/data/threatstack/licensekey
      property: licensekey
{{- end }}

{{- if .Values.external_secrets_operator.setup_threatstack_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "threatstack"
  namespace: "threatstack"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "threatstack"
  data:
  - secretKey: licensekey
    remoteRef:
      key: threatstack/licensekey
      property: licensekey
{{- end }}