{{- if .Values.external_secrets.setup_prometheus_metrics_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "metrics"
  namespace: monitoring
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: password
      key: secret/data/prometheus/metrics
      property: password
    - name: username
      key: secret/data/prometheus/metrics
      property: username
{{- end }}