{{- if .Values.external_secrets.setup_argocd_secret }}
apiVersion: 'kubernetes-client.io/v1'
kind: 'ExternalSecret'
metadata:
  name: "argocd-secret"
  namespace: argocd
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: oidc.dex.clientId
      key: secret/data/{{ .Values.external_secrets.argocd_secret_oidc_vault_key }}/dex
      property: clientId
    - name: oidc.dex.clientSecret
      key: secret/data/{{ .Values.external_secrets.argocd_secret_oidc_vault_key }}/dex
      property: clientSecret
    - name: server.secretkey
      key: secret/data/argocd
      property: serverSecretKey
{{- end }}