{{- if .Values.external_secrets.setup_argocd_secret }}
apiVersion: 'kubernetes-client.io/v1'
kind: 'ExternalSecret'
metadata:
  name: "argocd-secret"
  namespace: argocd
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: oidc.dex.clientId
      key: secret/data/{{ .Values.external_secrets.argocd_secret_oidc_vault_key }}/dex
      property: clientId
    - name: oidc.dex.clientSecret
      key: secret/data/{{ .Values.external_secrets.argocd_secret_oidc_vault_key }}/dex
      property: clientSecret
    - name: server.secretkey
      key: secret/data/argocd
      property: serverSecretKey
{{- end }}
{{- if .Values.external_secrets_operator.setup_argocd_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "argocd-secret"
  namespace: argocd
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: argocd-secret
  data:
  - secretKey: oidc.dex.clientId
    remoteRef:
      key: {{ .Values.external_secrets_operator.argocd_secret_oidc_vault_key }}/dex
      property: clientId
  - secretKey: oidc.dex.clientSecret
    remoteRef:
      key: {{ .Values.external_secrets_operator.argocd_secret_oidc_vault_key }}/dex
      property: clientSecret
  - secretKey: server.secretkey
    remoteRef:
      key: argocd
      property: serverSecretKey
{{- end }}