{{- if .Values.external_secrets.setup_loki_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "loki-ingress-auth"
  namespace: loki
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: auth
      key: secret/data/logging/loki
      property: ingress-auth
{{- end }}