{{- if .Values.external_secrets.setup_github_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "github"
  namespace: argocd
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: sshPrivateKey
      key: secret/data/token/github
      property: sshPrivateKey
{{- end }}