{{- if .Values.external_secrets.setup_gatekeeper_policy_manager_secret }}
apiVersion: 'kubernetes-client.io/v1'
kind: 'ExternalSecret'
metadata:
  name: "gpm-secrets"
  namespace: gatekeeper-policy-manager
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - key: secret/data/oidc/dex
      name: oidc.dex.clientId
      property: clientId
    - key: secret/data/oidc/dex
      name: oidc.dex.clientSecret
      property: clientSecret
{{- end }}

{{- if .Values.external_secrets_operator.setup_gatekeeper_policy_manager_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "gpm-secrets"
  namespace: "gatekeeper-policy-manager"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "gpm-secrets"
  data:
  - secretKey: oidc.dex.clientId
    remoteRef:
      key: oidc/dex
      property: clientId
  - secretKey: oidc.dex.clientSecret
    remoteRef:
      key: oidc/dex
      property: clientSecret
{{- end }}