{{- if .Values.kubedb_catalog.setup_mongodb_3_6 }}
apiVersion: 'catalog.kubedb.com/v1alpha1'
kind: 'MongoDBVersion'
metadata:
  name: "3.6.13"
  labels:
    app: kubedb
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  db:
    image: 'kubedb/mongo:3.6.13'
  exporter:
    image: 'kubedb/mongodb_exporter:v1.0.0'
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot
  tools:
    image: 'kubedb/mongo-tools:3.6.13'
  version: 3.6.13
{{- end }}