{{- if .Values.kubedb_catalog.setup_mongodb_4_0 }}
apiVersion: 'catalog.kubedb.com/v1alpha1'
kind: 'MongoDBVersion'
metadata:
  name: "4.0.11"
  labels:
    app: kubedb
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  db:
    image: 'kubedb/mongo:4.0.11'
  exporter:
    image: 'kubedb/mongodb_exporter:v1.0.0'
  initContainer:
    image: kubedb/busybox
  podSecurityPolicies:
    databasePolicyName: mongodb-db
    snapshotterPolicyName: mongodb-snapshot
  tools:
    image: 'kubedb/mongo-tools:4.0.11'
  version: 4.0.11
{{- end }}