apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lacework-agent.name" . }}-access-token
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    tier: monitoring
    app: {{ include "lacework-agent.name" . }}
type: Opaque
data:
  agent-access-token: {{ required "A valid AccessToken is required! Specify your Lacework agent token in values.yaml" .Values.laceworkConfig.accessToken | b64enc }}
