apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
  namespace: {{ .Release.Namespace }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  config.json: |
    {
      "serverurl": "{{ .Values.laceworkConfig.serverUrl}}",
      "autoupgrade": "{{ required "A value for autoupgrade is required" .Values.laceworkConfig.autoUpgrade }}",
      "tags": {
        "Env": "{{ .Values.laceworkConfig.env }}"
{{- if .Values.laceworkConfig.kubernetesCluster }},
        "KubernetesCluster" :"{{ .Values.laceworkConfig.kubernetesCluster}}"
{{- end }}
      }
    }
