apiVersion: v1
kind: Service
metadata:
  name: enroute-admin
  labels:
    {{- include "enroute.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: metrics-envoy
      port: 8002
      targetPort: metrics-envoy
      protocol: TCP
    - name: metrics-enroute
      port: 8000
      targetPort: metrics-enroute
      protocol: TCP
  selector:
    {{- include "enroute.selectorLabels" . | nindent 4 }}
  type: ClusterIP
