{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-sync.serviceAccountName" . }}
  labels:
    {{- include "cert-manager-sync.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccountIrsaArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountIrsaArn | quote }}
    {{- end }}
    {{ with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
