apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    n8nComponent: webhook
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      n8nComponent: webhook
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        n8nComponent: webhook
        {{- include "n8n.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "n8n.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.webhook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args: {{- .Values.webhook.args | toYaml | nindent 12 }}
          securityContext: {{- toYaml .Values.webhook.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ (merge .Values.webhook.env .Values.global.env).N8N_PORT }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            periodSeconds: 60
            initialDelaySeconds: 5
            successThreshold: 1
            timeoutSeconds: 30
            httpGet:
              path: /healthz
              port: {{ (merge .Values.webhook.env .Values.global.env).N8N_PORT }}
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 20
            initialDelaySeconds: 5
            successThreshold: 1
            timeoutSeconds: 2
            httpGet:
              path: /healthz
              port: {{ (merge .Values.webhook.env .Values.global.env).N8N_PORT }}
          startupProbe:
            failureThreshold: 180
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: {{ (merge .Values.webhook.env .Values.global.env).N8N_PORT }}
          env: {{- include "renderEnvVarsMap" (merge .Values.webhook.env .Values.global.env ) | indent 12}}
          lifecycle:
            # Send SIGINT to the process to close it's databases
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - kill -2 1
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
