apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    n8nComponent: webhook
    {{- include "n8n.selectorLabels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    n8nComponent: webhook
    {{- include "n8n.selectorLabels" . | nindent 4}}
