dependencies:
  - name: splunk-kubernetes-logging
    condition: splunk-kubernetes-logging.enabled
  - name: splunk-kubernetes-objects
    condition: splunk-kubernetes-objects.enabled
  - name: splunk-kubernetes-metrics
    condition: splunk-kubernetes-metrics.enabled
