dependencies:
  - name: splunk-kubernetes-logging
    version: 1.5.4
    repository: file://charts/splunk-kubernetes-logging
    condition: splunk-kubernetes-logging.enabled
  - name: splunk-kubernetes-objects
    version: 1.5.4
    repository: file://charts/splunk-kubernetes-objects
    condition: splunk-kubernetes-objects.enabled
  - name: splunk-kubernetes-metrics
    version: 1.5.4
    repository: file://charts/splunk-kubernetes-metrics
    condition: splunk-kubernetes-metrics.enabled
