# Default values for istio-additions.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## edge-stack configuration(s) for ServiceMesh (Used exclusively for packaging)
edge_stack:
  setup_tracingservice:
    enabled: false
    tracing_uri: 'jaeger-aio-collector.istio-system.svc.cluster.local:9411'
  setup_tlscontext:
    enabled: false

## Ambassador configuration(s) for ServiceMesh (To be deprecated, after K8s 1.23+, generated at runtime in TF)
ambassador:
  setup_tracingservice:
    enabled: false
    tracing_uri: 'jaeger-aio-collector.istio-system.svc.cluster.local:9411'
  setup_tlscontext:
    enabled: false

## Istio
istio:
  ### ServiceMonitor configuration(s)
  serviceMonitor:
    enabled: false
  ### Enable PeerAuthentication for auxiliary components
  peerAuthentication:
    setup_vault:
      enabled: false
      mode: PERMISSIVE
    setup_vault_secrets_webhook:
      enabled: false
      mode: PERMISSIVE
    setup_bitnami_redis:
      enabled: false
      mode: PERMISSIVE
    setup_bitnami_mongodb:
      enabled: false
      mode: PERMISSIVE

## Management console for an Istio-based service mesh
kiali:
  basic_config:
    enabled: false
    image:
      override: false
      repository: quay.io/kiali/kiali
      tag: v1.59.1
    ingress:
      enabled: false
      host: 'kiali.example.bluescape.io'
    in_cluster_urls:
      grafana: 'http://grafana-service.grafana.svc:3000'
      prometheus: 'http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090'
      tracing: 'http://jaeger-aio-query.istio-system.svc.cluster.local:16686/jaeger'
  prod_config:
    enabled: false
    image:
      override: false
      repository: quay.io/kiali/kiali
      tag: v1.59.1
    ingress:
      enabled: false
      host: 'kiali.example.bluescape.io'
    in_cluster_urls:
      grafana: 'http://grafana-service.grafana.svc:3000'
      prometheus: 'http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090'
      tracing: 'http://jaeger-aio-query.istio-system.svc.cluster.local:16686/jaeger'

## Open source end-to-end distributed tracing system
jaeger:
  basic_config:
    enabled: false
    image:
      repository: jaegertracing/all-in-one
      tag: 1.39.0
    ingress:
      enabled: false
  prod_config:
    enabled: false
    image:
      repository: jaegertracing/all-in-one
      tag: 1.39.0
    ingress:
      enabled: false