# Default values for bluescape-eks-aux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vault_cr:
  enabled: false
  image: vault
  imageTag: "1.6.0"
  bound_service_account_names: []
  bound_service_account_namespaces: []
  storageClass: "persistent"
  clusterSize: 3
  serviceAccount: "vault"
  priorityClassName: "system-node-critical"
  tls_disable: false
  istio_enable: false
  local_vault_addr: "https://vault.vault.svc.cluster.local:8200"
  setup_vault_as_cluster_secret_store: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node.kubernetes.io/lifecycle
                operator: NotIn
                values:
                  - spot
cert_manager:
  setup_letsencrypt_prod_cluster_issuer: false
  setup_letsencrypt_prod_cluster_dns_issuer: false
  setup_letsencrypt_extra_cluster_issuer:
    enabled: false
    name: "letsencrypt-extra"
    access_key_id: ABCDEFXXXXXXX
    region: us-east-1
    dns_zone: bluescape.com
    hosted_zone_id: ''
    email: ops@bluescape.com
    role: ''
    cname_strategy: None
    acme_server: 'https://acme-v02.api.letsencrypt.org/directory' # Production URL
    #acme_server: 'https://acme-staging-v02.api.letsencrypt.org/directory' # Staging URL for Testing
    preferred_chain: 'ISRG Root X1' # Specify a CA’s common name for the certificate to be issued by

external_secrets:
  setup_legacy_extra_cluster_issuer_secret: false
  cluster_issuer_name: ""

  setup_gatekeeper_policy_manager_secret: false
  setup_prometheus_metrics_secret: false
  setup_threatstack_secret: false
  setup_argocd_secret: false
  setup_github_secret: false
  setup_loki_secret: false

  setup_aes_edge_stack_secret: false
  aes_edge_stack_secret_name: ""

  argocd_secret_oidc_vault_key: oidc

kubedb_catalog:
  setup_mongodb_3_6: false
  setup_mongodb_4_0: false
  setup_mysql_5_6: false
  setup_postgres_11_1: false

external_secrets_operator:
  setup_cluster_secret_store_for_vault: false

  setup_legacy_extra_cluster_issuer_secret: false
  cluster_issuer_name: ""

  setup_gatekeeper_policy_manager_secret: false
  setup_prometheus_metrics_secret: false
  setup_threatstack_secret: false
  setup_argocd_secret: false
  setup_github_secret: false
  setup_loki_secret: false

  setup_aes_edge_stack_secret: false
  aes_edge_stack_secret_name: ""

  argocd_secret_oidc_vault_key: oidc

