{{- if .Values.contour.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contour.fullname" . }}-contour
  labels: {{- include "contour.labels" . | nindent 4 }}
    app.kubernetes.io/component: contour
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This value of maxSurge means that during a rolling update
      # the new ReplicaSet will be created first.
      maxSurge: 50%
  selector:
    matchLabels: {{- include "contour.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: contour
  template:
    metadata:
      {{- if .Values.configInline }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels: {{- include "contour.labels" . | nindent 8 }}
        app.kubernetes.io/component: contour
    spec: {{- include "contour.imagePullSecrets" . | nindent 6 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels: {{- include "contour.matchLabels" . | nindent 18 }}
                  app.kubernetes.io/component: contour
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- if .Values.contour.affinity }}
{{- include "contour.tplValue" (dict "value" .Values.contour.nodeSelector "context" $) | indent 8 }}
      {{- end }}
      {{- if .Values.contour.nodeSelector }}
      nodeSelector: {{- include "contour.tplValue" (dict "value" .Values.contour.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.contour.affinity }}
      affinity: {{- include "contour.tplValue" (dict "value" .Values.contour.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.contour.tolerations}}
      tolerations: {{- include "contour.tplValue" (dict "value" .Values.contour.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - contour
        args:
        - serve
        - --incluster
        - --xds-address=0.0.0.0
        - --xds-port=8001
        - --envoy-service-http-port=80
        - --envoy-service-https-port=443
        - --contour-cafile=/certs/ca.crt
        - --contour-cert-file=/certs/tls.crt
        - --contour-key-file=/certs/tls.key
        - --config-path=/config/contour.yaml
        {{- if .Values.ingressClass }}
        - --ingress-class-name={{ .Values.ingressClass }}
        {{- end }}
        image: {{ include "contour.image" . }}
        imagePullPolicy: {{ .Values.contour.image.pullPolicy }}
        name: contour
        ports:
        - containerPort: 8001
          name: xds
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
      {{- if .Values.contour.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: {{ .Values.contour.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.contour.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.contour.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.contour.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.contour.livenessProbe.failureThreshold }}
      {{- end }}
      {{- if .Values.contour.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: {{ .Values.contour.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.contour.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.contour.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.contour.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.contour.readinessProbe.failureThreshold }}
      {{- end }}
        resources:
{{ toYaml .Values.contour.resources | indent 10 }}
        volumeMounts:
        - name: contourcert
          mountPath: /certs
          readOnly: true
        - name: contour-config
          mountPath: /config
          readOnly: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      dnsPolicy: ClusterFirst
      serviceAccountName: {{ include "contour.contourServiceAccountName" . }}
      {{- if .Values.contour.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.contour.securityContext.runAsUser }}
        runAsGroup: {{ .Values.contour.securityContext.runAsGroup }}
        fsGroup: {{ .Values.contour.securityContext.fsGroup }}
        runAsNonRoot: {{ .Values.contour.securityContext.runAsNonRoot }}
      {{- end }}
      volumes:
      - name: contourcert
        secret:
          secretName: contourcert
      - name: contour-config
        configMap:
          name: {{ include "contour.configMapName" . }}
          defaultMode: 0644
          items:
          - key: contour.yaml
            path: contour.yaml
{{- end }}
