apiVersion: v2
name: gateway
description: Helm chart for deploying Istio gateways
type: application
version: 1.18.2
appVersion: 1.18.2
sources:
- https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways