## Reference : https://www.getambassador.io/docs/edge-stack/latest/topics/running/services/tracing-service/
{{- if .Values.edge_stack.setup_tracingservice.enabled }}
apiVersion: getambassador.io/v2
kind: TracingService
metadata:
  name:  tracing
  namespace: edge-stack
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    {{- include "istio-additions.labels" . | nindent 4 }}
spec:
  service: {{ .Values.edge_stack.setup_tracingservice.tracing_uri }}
  driver: zipkin
  config: {}
  tag_headers:
    - ":authority"
    - ":path"
{{- end }}