{{- if .Values.istio.peerauthentication.setup_vault.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app: security
    {{- include "istio-additions.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.istio.peerauthentication.setup_vault.mode }}
{{- end }}