{{- if .Values.istio.peerauthentication.setup_bluescape_ns }}
{{- $top := . -}}
{{- range $index, $peernsobj := .Values.istio.peerauthentication.setup_bluescape_ns }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "{{ lower $peernsobj.namespace }}-{{ lower $peernsobj.mode }}"
  namespace: {{ $peernsobj.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app: security
spec:
  mtls:
    mode: {{ $peernsobj.mode }}
{{- end }}
{{- end }}