{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-auth-reader" (include "common.names.fullname" .) }}
  namespace: kube-system
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
