apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stunnel.fullname" . }}
  labels:
    {{- include "stunnel.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "stunnel.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "stunnel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stunnel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      volumes:
        {{- toYaml .Values.volumes | default "" | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace 
          - name: STUNNEL_PATH
            value: '/etc/stunnel'
          - name: NXLOG_SERVICE_IP_WITH_PORT
            value: "{{ .Release.Name }}-nxlog-ce:8080"
          - name: BIT_KEY_SIZE
            value: '4096'
          - name: CERT_VALIDITY_IN_DAYS
            value: '1024'
          - name: CERT_PARAMS
            value:  "/C=US/ST=California/L=San Carlos/O=Bluescape/CN={{- with (index .Values.ingress.hosts 0) }}{{ .host }}{{- end }}"
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
          stdin: false
          tty: false
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-6000
              containerPort: 6000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
