{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "stunnel.fullname" $ }}
  labels:
    {{- include "stunnel.labels" . | nindent 4 }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.org/ssl-services: '{{ include "stunnel.fullname" $ }}'
  {{- end }}
{{- else }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "stunnel.fullname" $ }}
                port:
                  number: 6000
    {{- end }}
    {{- else -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: {{ include "stunnel.fullname" $ }}
              servicePort: 6000
    {{- end }}
    {{- end -}}
  {{- end }}
