apiVersion: v1
kind: Service
metadata:
  name: {{ include "stunnel.fullname" . }}
  labels:
    {{- include "stunnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: tcp-6000
  selector:
    {{- include "stunnel.selectorLabels" . | nindent 4 }}
