---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rotatingcredentials.sretools.bluescape.io
  # https://github.io/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a..."
spec:
  group: sretools.bluescape.io
  names:
    kind: RotatingCredential
    singular: rotatingcredential
    plural: rotatingcredentials
    shortNames:
    - dbrc
    - dbrcs
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: "RotatingCredential is the Schema for the rotatingcredentials API. This is a custom resource definition for managing rotating credentials for databases."
        type: object
        properties:
          spec:
            description: "RotatingCredential CR spec."
            type: object
            required:
            - db_type
            - image
            properties:
              image:
                type: string
              db_type:
                type: string
                enum: ['mysql', 'postgres', 'mongodb']
              credentials:
                type: object
                properties:
                  # give the ability to specify the vault address, but this will
                  # only be used as a last resort if discovery doesn't work properly
                  vault_addr:
                    type: string
                    default: https://vault.vault:8200
                  admin:
                    type: object
                    properties:
                      vault_path:
                        type: string
                      root_username:
                        type: string
                      root_password:
                        type: string
                    required:
                    - vault_path
                    - root_username
                    - root_password
                  user:
                    type: object
                    properties:
                      vault_path:
                        type: string
                      vault_username:
                        type: string
                      vault_password:
                        type: string
                    required:
                    - vault_path
                    - vault_username
                    - vault_password
                required:
                - vault_addr
              # rotate_lead_time:
              #   type: string
              #   default: "14d"
              force_rotation:
                type: boolean
                default: false
              password_matchre_rule:
                x-kubernetes-preserve-unknown-fields: true
                type: string
                default: '[\d\w\-\._]+'
              password_byte_count:
                type: integer
                default: 32
                minimum: 15
                maximum: 256
              cronjob_name:
                type: string
              rotation_mm_hh:
                type: string
              # default: "00 07"
              zero_downtime_rotation:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  username_prefix:
                    type: string
                    default: zdt
          status:
            description: "The status for the CR. This is where the operator will store the current state of the CR."
            type: object
            properties:
              # type of database (db, postgres, mongo)
              db_type:
                type: string
              # the username to be changed extracted from vault
              username:
                type: string
              # data base hostname where rotated user creds reside
              db_hostname:
                type: string
              # the phase currently running in control loop
              phase:
                type: string
              # Actual expiration
              expiration:
                type: string
              # timestamp recorded in database of last rotation
              # note: this value is sourced from the database not the operator
              last_rotation:
                type: string
              # timestamp calculated by days-to-expire + lastRotated
              next_rotation_eligible:
                description: "Next Rotation Eligibility"
                type: string
                default: ""
              # password last changed
              password_last_changed:
                type: string
              # password expired
              password_expired:
                type: string
              password_lifetime:
                type: integer
              cronjob_name:
                description: "Cronjob Name"
                type: string
              # within_job_window
              within_job_window:
                type: boolean
              host:
                type: string
              pod_watcher:
                description: "Pod Watcher Active"
                type: boolean
              nre_override:
                description: "Next Rotation Eligibility Override"
                type: string
                default: ""
              rotation:
                type: object
                description: "Rotation Status"
                properties:
                  success:
                    type: boolean
                    default: false
                  attempts:
                    type: integer
                    default: 0
                  failed:
                    type: integer
                    default: 0
                  pod_name:
                    type: string
    subresources:
      status: {}
    additionalPrinterColumns:
      - name: DB Type
        type: string
        description: The database type
        jsonPath: .spec.db_type
      - name: DB Username Key
        type: string
        description: The username to be rotated
        jsonPath: .status.username
      - name: DB Hostname
        type: string
        description: The database hostname/instance on which the user getting rotated resides
        jsonPath: .status.db_hostname
      - name: Phase
        type: string
        description: Date of the last time credentials were rotated
        jsonPath: .status.phase
      - name: Expiration
        type: string
        description: Actual credential expiration
        jsonPath: .status.expiration
      - name: Last Rotation
        type: string
        description: Date of the last time credentials were rotated
        jsonPath: .status.last_rotation
      - name: Next Rotation Eligibility
        type: string
        description: Date of next eligible rotation
        jsonPath: .status.next_rotation_eligible
      - name: Cronjob Name
        type: string
        description: Cronjob name
        jsonPath: .status.cronjob_name
