{{- if .Values.dbShimConfigMap}}
{{- if .Values.dbShimConfigMap.create}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "db-shim-configmap.name" .}}-db-shim
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "credrotator-operator.labels" . | nindent 4}}
  {{- with .Values.dbShimConfigMap.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.dbShimConfigMap.config }}
  config: |
  {{- with .Values.dbShimConfigMap.config }}
  {{ . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
