---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialrotation-operator-rb-clusterrole
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["sretools.bluescape.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["vault.banzaicloud.com"]
  resources: ["*"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: credentialrotation-operator-rb-clusterrolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: credentialrotation-operator-rb-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "credrotator-operator.serviceAccountName" . }}
  namespace:  {{ .Release.Namespace }}
