{{- $root := . -}}
{{- with .Values.services }}
  {{- range $key, $value := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    {{- include "credrotator-operator.labels" $root | nindent 4}}
spec:
  type: {{$value.type}}
  ports:
    {{- with $value.ports}}
    {{- range $pkey, $pvalue := .}}
    - name: {{$pvalue.name}}
      port: {{$pvalue.port}}
      targetPort: {{$pvalue.targetPort}}
      protocol: {{$pvalue.protocol}}
    {{- end}}
    {{- end}}
  selector:
    {{- include "credrotator-operator.selectorLabels" $root | nindent 4}}
    {{- end }}
    {{- end }}