{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
# may not be necessary anymore but...
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: {{ include "credrotator-operator.serviceAccountName" . }}
  labels:
    {{- include "credrotator-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- . | toYaml | nindent 4 }}
{{- end }}
{{- end }}
