{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grafana-operator.fullname" . }}
  labels: {{- include "grafana-operator.labels" . | nindent 4 }}
roleRef:
  name: {{ include "grafana-operator.fullname" . }}
  kind: Role
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: {{ include "grafana-operator.serviceAccountName" . }}
{{- end  }}
