apiVersion: v1
appVersion: 1.20.6-tetrate0-alpha1
description: Helm chart for a remote cluster using an external istio control plane
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- external-istiod
name: istiod-remote
sources:
- https://github.com/istio/istio
version: 1.20.6+tetrate0-alpha1
