apiVersion: v1
kind: Service
metadata:
  name: {{ include "cdata.fullname" . }}
  labels:
    {{- include "cdata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "cdata.selectorLabels" . | nindent 4 }}
