{{- if .Values.grafana.external_secrets.setup_grafana_oidc_secret }}
apiVersion: 'kubernetes-client.io/v1'
kind: 'ExternalSecret'
metadata:
  name: "grafana-oidc-auth"
  labels:
    labels: {{- include "bluescape-monitoring-grafana.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      key: secret/data/oidc/dex
      property: clientId
    - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      key: secret/data/oidc/dex
      property: clientSecret
{{- end }}

{{- if .Values.grafana.external_secrets_operator.setup_grafana_oidc_secret }}
apiVersion: 'external-secrets.io/v1beta1'
kind: 'ExternalSecret'
metadata:
  name: "grafana-oidc-auth"
  namespace: "grafana"
  labels:
    {{- include "bluescape-monitoring-grafana.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend-cs
    kind: ClusterSecretStore
  target:
    name: "grafana-oidc-auth"
  data:
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    remoteRef:
      key: oidc/dex
      property: clientId
  - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
    remoteRef:
      key: oidc/dex
      property: clientSecret
{{- end }}

