{{- if gt (len .Values.grafana.env) 0 }}
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Release.Name }}-grafana-env-vars"
    labels: {{- include "bluescape-monitoring-grafana.labels" . | nindent 6 }}
stringData:
  {{- range $k, $v := .Values.grafana.env }}
  {{- range $kk, $vv := $v }}
  {{ $kk }}: "{{ $vv }}"
  {{- end }}
  {{- end }}
{{- end }}