{{- if ne .Values.grafana.pluginInstallString "" }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-install-plugins
  labels: {{- include "bluescape-monitoring-grafana.labels" . | nindent 6 }}
type: Opaque
stringData:
  GF_INSTALL_PLUGINS: {{ .Values.grafana.pluginInstallString }}
{{- end }}