{{- if .Values.grafana.ha_mode }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  annotations:
    "helm.sh/hook": "post-install"
  name: postgres-grafana
spec:
  replicas: 3
  standbyMode: hot
  databaseSecret:
    secretName: postgres-grafana-auth
  init:
    scriptSource:
      configMap:
        name: postgres-grafana-init-script
  leaderElection:
    leaseDurationSeconds: 15
    renewDeadlineSeconds: 10
    retryPeriodSeconds: 2
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      resources: {}
      serviceAccountName: postgres
  replicaServiceTemplate:
    metadata: {}
    spec: {}
  serviceTemplate:
    metadata: {}
    spec: {}
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: persistent
  storageType: Durable
  terminationPolicy: WipeOut
  updateStrategy:
    type: RollingUpdate
  version: "11.1"
{{- end }}