{{- if .Values.grafana.ha_mode }}
apiVersion: v1
data:
  init.sql: |
    CREATE DATABASE grafana;
kind: ConfigMap
metadata:
  name: postgres-grafana-init-script
  labels:
    name: postgres-grafana-init-script
    {{- include "bluescape-monitoring-grafana.labels" . | nindent 4 }}
{{- end }}